CREATE DATABASE EMPLOYEEDB;
USE EMPLOYEEDB;

CREATE TABLE EMPLOYEE(
	EMP_ID INT NOT NULL auto_increment,
	NAME VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(70),
	DOB DATETIME NOT NULL,
	ADDRESS VARCHAR(500) NOT NULL,
	POSITION VARCHAR(50),
	REPORTSTO VARCHAR(50),
	TELEPHONE BIGINT NOT NULL UNIQUE,
	GENDER VARCHAR(1),
	SALARY BIGINT,
	DATIME TIMESTAMP,
	
	primary key ( EMP_ID )
);
