--CREATE DATABASE EMPLOYEEDB;
--USE EMPLOYEEDB;

CREATE TABLE EMPLOYEE(	EMP_ID INT IDENTITY  ,	NAME VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(70),
	DOB VARCHAR(70) NOT NULL,
	ADDRESS VARCHAR(500) NOT NULL,
	POSITION VARCHAR(50),
	REPORTSTO VARCHAR(50),
	TELEPHONE BIGINT NOT NULL UNIQUE,
	GENDER VARCHAR(1),
	SALARY BIGINT,
	DATIME DATETIME,
	
	primary key ( EMP_ID )
);
